# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Reseplaneraren.Model.Color do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :bgColor,
    :fgColor,
    :stroke
  ]

  @type t :: %__MODULE__{
          :bgColor => String.t(),
          :fgColor => String.t(),
          :stroke => String.t()
        }
end

defimpl Poison.Decoder, for: Reseplaneraren.Model.Color do
  def decode(value, _options) do
    value
  end
end
