# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Reseplaneraren.Model.CreationDate do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :"$"
  ]

  @type t :: %__MODULE__{
          :"$" => Date.t()
        }
end

defimpl Poison.Decoder, for: Reseplaneraren.Model.CreationDate do
  import Reseplaneraren.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:"$", :date, nil, options)
  end
end
