# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Reseplaneraren.Model.Direction do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :routeIdxTo,
    :"$",
    :routeIdxFrom
  ]

  @type t :: %__MODULE__{
          :routeIdxTo => integer(),
          :"$" => String.t(),
          :routeIdxFrom => integer()
        }
end

defimpl Poison.Decoder, for: Reseplaneraren.Model.Direction do
  def decode(value, _options) do
    value
  end
end
