# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Reseplaneraren.Model.GeometryRef do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :ref
  ]

  @type t :: %__MODULE__{
          :ref => String.t()
        }
end

defimpl Poison.Decoder, for: Reseplaneraren.Model.GeometryRef do
  def decode(value, _options) do
    value
  end
end
