# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Reseplaneraren.Model.JourneyType do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"routeIdxTo",
    :"routeIdxFrom",
    :"type"
  ]

  @type t :: %__MODULE__{
    :"routeIdxTo" => integer(),
    :"routeIdxFrom" => integer(),
    :"type" => String.t
  }
end

defimpl Poison.Decoder, for: Reseplaneraren.Model.JourneyType do
  def decode(value, _options) do
    value
  end
end

