# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Reseplaneraren.Model.Note do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :priority,
    :severity,
    :key
  ]

  @type t :: %__MODULE__{
          :priority => String.t(),
          :severity => String.t(),
          :key => String.t()
        }
end

defimpl Poison.Decoder, for: Reseplaneraren.Model.Note do
  def decode(value, _options) do
    value
  end
end
