# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Reseplaneraren.Model.Notes do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Note
  ]

  @type t :: %__MODULE__{
          :Note => [Note]
        }
end

defimpl Poison.Decoder, for: Reseplaneraren.Model.Notes do
  import Reseplaneraren.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:Note, :list, Reseplaneraren.Model.Note, options)
  end
end
