# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Reseplaneraren.Model.Origin do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"routeIdx",
    :"$",
    :"cancelled",
    :"track",
    :"rtTrack",
    :"type",
    :"date",
    :"Notes",
    :"id",
    :"rtDate",
    :"time",
    :"directdate",
    :"name",
    :"rtTime",
    :"directtime"
  ]

  @type t :: %__MODULE__{
    :"routeIdx" => String.t,
    :"$" => String.t,
    :"cancelled" => boolean(),
    :"track" => String.t,
    :"rtTrack" => String.t,
    :"type" => String.t,
    :"date" => Date.t,
    :"Notes" => Notes,
    :"id" => String.t,
    :"rtDate" => Date.t,
    :"time" => String.t,
    :"directdate" => Date.t,
    :"name" => String.t,
    :"rtTime" => String.t,
    :"directtime" => String.t
  }
end

defimpl Poison.Decoder, for: Reseplaneraren.Model.Origin do
  import Reseplaneraren.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"date", :date, nil, options)
    |> deserialize(:"Notes", :struct, Reseplaneraren.Model.Notes, options)
    |> deserialize(:"rtDate", :date, nil, options)
    |> deserialize(:"directdate", :date, nil, options)
  end
end

