# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Reseplaneraren.Model.SystemInfo do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :TimetableInfo,
    :errorText,
    :error,
    :serverdate,
    :servertime,
    :noNamespaceSchemaLocation
  ]

  @type t :: %__MODULE__{
          :TimetableInfo => TimetableInfo,
          :errorText => String.t(),
          :error => String.t(),
          :serverdate => Date.t(),
          :servertime => String.t(),
          :noNamespaceSchemaLocation => String.t()
        }
end

defimpl Poison.Decoder, for: Reseplaneraren.Model.SystemInfo do
  import Reseplaneraren.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:TimetableInfo, :struct, Reseplaneraren.Model.TimetableInfo, options)
    |> deserialize(:serverdate, :date, nil, options)
  end
end
