# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Reseplaneraren.Model.TimetableInfo do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :TimeTableData,
    :TimeTablePeriod
  ]

  @type t :: %__MODULE__{
          :TimeTableData => TimeTableData,
          :TimeTablePeriod => TimeTablePeriod
        }
end

defimpl Poison.Decoder, for: Reseplaneraren.Model.TimetableInfo do
  import Reseplaneraren.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:TimeTableData, :struct, Reseplaneraren.Model.TimeTableData, options)
    |> deserialize(:TimeTablePeriod, :struct, Reseplaneraren.Model.TimeTablePeriod, options)
  end
end
