# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Reseplaneraren.Model.TripList do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"errorText",
    :"error",
    :"serverdate",
    :"servertime",
    :"Trip",
    :"noNamespaceSchemaLocation"
  ]

  @type t :: %__MODULE__{
    :"errorText" => String.t,
    :"error" => String.t,
    :"serverdate" => Date.t,
    :"servertime" => String.t,
    :"Trip" => [Trip],
    :"noNamespaceSchemaLocation" => String.t
  }
end

defimpl Poison.Decoder, for: Reseplaneraren.Model.TripList do
  import Reseplaneraren.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"serverdate", :date, nil, options)
    |> deserialize(:"Trip", :list, Reseplaneraren.Model.Trip, options)
  end
end

