# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Reseplaneraren.Model.Trip do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Leg,
    :travelWarranty,
    :valid,
    :alternative,
    :type
  ]

  @type t :: %__MODULE__{
          :Leg => [Leg],
          :travelWarranty => boolean(),
          :valid => boolean(),
          :alternative => boolean(),
          :type => String.t()
        }
end

defimpl Poison.Decoder, for: Reseplaneraren.Model.Trip do
  import Reseplaneraren.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:Leg, :list, Reseplaneraren.Model.Leg, options)
  end
end
