# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Reseplaneraren.Api.Livemap do
  @moduledoc """
  API calls for all endpoints tagged `Livemap`.
  """

  alias Reseplaneraren.Connection
  import Reseplaneraren.RequestBuilder

  @doc """
  Returns the positions of all vehicles in a given bounding box
  This method will return the positions of all vehicles in a given bounding box.

  ## Parameters

  - connection (Reseplaneraren.Connection): Connection to server
  - minx (String.t): Left border (longitude) of the bounding box in WGS84 * 1000000
  - maxx (String.t): Right border (longitude) of the bounding box in WGS84 * 1000000
  - miny (String.t): Lower border (latitude) of the bounding box in WGS84 * 1000000
  - maxy (String.t): Upper border (latitude) of the bounding box in WGS84 * 1000000
  - only_realtime (String.t): Can be used to define whether all vehicles should be returned or only those  vehicles which have realtime information. If it is set to yes, only vehicles  with realtime information are returned, if it is set to no, all vehicles in the  bounding box are returned.
  - opts (KeywordList): [optional] Optional parameters

  ## Returns

  {:ok, %Reseplaneraren.Model.LiveMap{}} on success
  {:error, info} on failure
  """
  @spec livemap(
          Tesla.Env.client(),
          String.t(),
          String.t(),
          String.t(),
          String.t(),
          String.t(),
          keyword()
        ) :: {:ok, Reseplaneraren.Model.LiveMap.t()} | {:error, Tesla.Env.t()}
  def livemap(connection, minx, maxx, miny, maxy, only_realtime, _opts \\ []) do
    %{}
    |> method(:get)
    |> url("/livemap")
    |> add_param(:query, :minx, minx)
    |> add_param(:query, :maxx, maxx)
    |> add_param(:query, :miny, miny)
    |> add_param(:query, :maxy, maxy)
    |> add_param(:query, :onlyRealtime, only_realtime)
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> decode(%Reseplaneraren.Model.LiveMap{})
  end
end
